@port = 3005

POST http://localhost:{{port}}/api/blogs
Content-Type: application/json

{
  "title": "fasfafaf",
  "author": "deafeeee",
  "url": "dasfasfasfa",
  "likes": 3,
  "user": "afasfafa"
}

###

GET http://localhost:{{port}}/api/blogs

###
PUT http://localhost:3005/api/blogs/60379a56326e3fd668396f3a
Content-Type: application/json

{
  "id": "60379a56326e3fd668396f3a",
  "title": "CHANGED",
  "author": "deeeee",
  "url": "dasfasfasfa",
  "likes": 3
}

