@port = 3005

POST http://localhost:{{port}}/api/users
Content-Type: application/json

{
  "username":"luca",
  "name":"cordero",
  "password" : "12345"
}

###

GET http://localhost:{{port}}/api/users
